trigger: 
- main

pool: 
   vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: Production VM Deploy
    resourceType: virtualMachine
    resourceName: vmdeploy # only deploy to the VM resource named RESOURCE-PC
  strategy:
    runOnce:
      deploy:   
          steps:
          - script: |
              pwd
              ls
              ls -al